### ISSUE TITLE
Cannot get Shadows back after using FPSSavior

### ISSUE THREAD

**Issue by 825i** [xinxs/ToS-Addons#1]
Heya,

After clicking any of the options on FPSSavior it seems character, enemy and pet shadows are permanently removed. Clicking the 'draw shadows' on/off doesn't do anything. Nor does removing the addon. It seems my shadows are permanently disabled and I have no way to re-enable them.

Could you please tell me how to re-enable them? If possible, it would be great that you allow Shadows to be on for HIGH but disable them for any other setting.

Using a Nvidia GTX 1050 with the latest version of the game and addon enabled.

I checked the addon files in my own directory but unfortunately I cannot find any kind of .ua file to edit to check these options myself. Just an .ipf file that I cannot read.

EDIT: I checked the .lua and I cannot see an option for adding the shadows back (or actually which option influences them) but it is likely that one of the options you disable causes shadows to be disabled also. Seeing as High mode still has some things disabled:

graphic.EnableBlur(0);  <----- _Could this be it?_

The others not enabled still in HIGH are:

graphic.EnableFastLoading(0);
graphic.EnableSharp(0);

Maybe it's just missing the shadow option completely, would that be maybe:

_graphic.EnableShadow(1);_

**Comment by xinxs** [comment]
Hi, sorry for the late reply,
Blur make the game look like this:
https://i.imgur.com/7CpMZtM.jpg
Sharp is similar making the game ugly.
Fast loading, I assume that the game ignores some settings to load fast.
The one that affect the shadows is graphic.EnableDepth(1).
You tried to set the shadows on in the game settings and after that setting the addon to HIGH?

**Comment by xinxs** [comment]
And you can set it in user.xml file: tosfolder/release/user.xml
change UseDepth="0" to 1. 
If the problem persist your user.xml maybe is corrupted, delete it and check the game files. (Will need to download some addon from manager, because some of the lua files used by addons get deleted when checking game files, downloading an addon from manager will download the files again).
