### ISSUE TITLE
assister plus ui was broken

### ISSUE THREAD

**Issue by elina7** [xinxs/ToS-Addons#5]
![image](https://user-images.githubusercontent.com/2672446/96260779-70953780-0ffa-11eb-83b8-c34445fa926a.png)
cant use assister ui
plz fix it

**Comment by xinxs** [comment]
Sorry for the late reply, and the assister ui update didnt come to Itos yet. So I cant test and fix it. This week patch also dont have any news. 
x.x

**Comment by xinxs** [comment]
Fixed now, use v1.1.2
